# Khipus.ai
## Fundamentals of Data Science 
### Python (NumPy):
### Name : (Your name here)
<span>© Copyright Notice 2025, Khipus.ai - All Rights Reserved.</span>

# Assignment 2



## Instructions
1. Complete each task below by filling in the appropriate code in the provided cells.
2. Ensure that your code runs without errors and produces the expected outputs.
3. Submit your completed notebook as instructed by your instructor.


# Import Numpy 

In [2]:
import numpy as np


## Task 1: Creating Arrays
Create a 1D NumPy array with values ranging from 10 to 50 (inclusive).

Expected output:

1D Array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]



In [ ]:
# Task 1 Solution
# <Your code here>


# Solution for Task 1

# 1D Array with values from 10 to 50
array_1d = np.arange(10, 51)
print("1D Array:", array_1d)



## Task 2: Array Operations
1. Use the two 1D arrays, `a` and `b`, each containing 5 random integers between 1 and 20.
2. Perform the following operations:
    - Add the two arrays element-wise.
    - Multiply the two arrays element-wise.

Expected output:

Array a: [ 2 11  1  2 15]

Array b: [ 6  7  5 19  5]

Addition: [ 8 18  6 21 20]

Multiplication: [12 77  5 38 75]


In [ ]:
# 1D arrays
a = np.random.randint(1, 21, size=5)
b = np.random.randint(1, 21, size=5)

print("Array a:", a)
print("Array b:", b)

# Task 2 Solution
# <Your code here>

# Solution for Task 2

# Element-wise addition
add_result = np.add(a, b)
print("Addition:", add_result)

# Element-wise multiplication
multiply_result = np.multiply(a, b)
print("Multiplication:", multiply_result)




## Task 3: Array Manipulation
1. Use the 2D array of shape (4, 5) with values ranging from 1 to 20.
2. Reshape the array into a shape of (5, 4).

Expected output:

Original 2D Array:

[[ 1  2  3  4  5]

 [ 6  7  8  9 10]

 [11 12 13 14 15]

 [16 17 18 19 20]]

Reshaped Array:

[[ 1  2  3  4]

 [ 5  6  7  8]

 [ 9 10 11 12]

 [13 14 15 16]

 [17 18 19 20]]


In [ ]:
# 2D array
array_2d = np.arange(1, 21).reshape(4, 5)
print("Original 2D Array:")
print(array_2d)

# Task 3 Solution

# <Your code here>

# Reshaping to (5, 4)
reshaped_array = array_2d.reshape(5, 4)
print("Reshaped Array:")
print(reshaped_array)
